ALTER TABLE Alunos
ADD COLUMN Sobrenome VARCHAR(100) NULL;

ALTER TABLE cursos
ADD COLUMN Area VARCHAR(100) NULL;

ALTER TABLE Alunos
CHANGE COLUMN  Telefeone Telefone VARCHAR(150) NULL;

ALTER TABLE Alunos
MODIFY COLUMN CPF VARCHAR(15);